### PR TITLE
fix(#10549): add constants for form and token_login doc types

### LINKED ISSUE #10549: Add constants for 'form' and 'token_login' document types

### PR DESCRIPTION
**Pull request by anurag2787**
# Description
This PR adds shared constants for the form and token_login document types and updates their usage in validation and token-login document creation

Resolves #10549

# Code review checklist

- [x] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [x] Tested: Unit and/or e2e where appropriate
- [x] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by anurag2787** [comment]
Hy @dianabarsan The PR is ready for review Thank!

File: ddocs/medic-db/medic/validate_doc_update.js [hunk 1]
```diff
@@ -9,7 +9,7 @@
 */
 function(newDoc, oldDoc, userCtx, secObj) {
 
-  var ADMIN_ONLY_TYPES = [ 'form', 'translations', 'token_login' ];
```
Comment (dianabarsan) [inline ddocs/medic-db/medic/validate_doc_update.js:12]: we still need to restrict token_login files. i don't understand the purpose of this change.

File: shared-libs/constants/src/index.js [hunk 2]
```diff
@@ -10,6 +10,8 @@ const DOC_IDS = {
 // Document Types
 const DOC_TYPES = {
   TRANSLATIONS: 'translations',
+  FORM: 'form',
```
Comment (dianabarsan) [inline shared-libs/constants/src/index.js]: it seems you added this type but are not using it. I think this could cause confusion. can you please remove the form type?

File: ddocs/medic-db/medic/validate_doc_update.js [hunk 3]
```diff
@@ -9,7 +9,7 @@
...
+  var ADMIN_ONLY_TYPES = ['form', 'translations', 'token_login'];
```
Comment (dianabarsan) [inline ddocs/medic-db/medic/validate_doc_update.js]: Can you please revert this change? The commit history will be confusing with this unnecessary change.

**Review by dianabarsan — COMMENTED** [review]
great! one tiny comment about git cleanup

File: ddocs/medic-db/medic/validate_doc_update.js (hunk 3 above)
Comment (anurag2787) [reply ddocs/medic-db/medic/validate_doc_update.js]: Sorry for this it was done by mistake i have reverted it
Thanks!
