### PR TITLE
fix: add safety checks to prevent race condition in contact summary

### LINKED ISSUE #10661: Race condition in loading contact summary
**Describe the bug**
I have an e2e test that loads the contact detail page of a contact. The contact is not special and I am using default config. Intermittently, I am getting a feedback doc logged about the contact-summary throwing an error. It's not a valid error, the error is caused by the contact summary function receiving an undefined contact. 

**To Reproduce**
1. Deploy latest CHT
2. Login as an offline user
3. Refresh the contact page and immediately click on a contact on the LHS
5. Check feedback docs

**Expected behavior**
No feedback docs should be logged. 

**Logs**
Example feedback doc: 
```
[
  {
    "_id": "feedback-2026-02-24T06:54:38.137Z-4f567e60-71fa-40cd-8438-f92150fc3495",
    "_rev": "1-eb0f458a4268e91a4abc368de490cf76",
    "arguments": [
      "\"Configuration error in contact-summary function: \"",
      "\"TypeError: Cannot read properties of undefined (reading 'type')\\n    at isReadyForNewPregnancy (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:67821)\\n    at 972 (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:69379)\\n    at n (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76381)\\n    at 344 (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:277)\\n    at n (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76381)\\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76492)\\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76500)\\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:158)\\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:223)\\n    at https://localhost/main.js:31432:27\""
    ],
    "info": {
      "message": "Cannot read properties of undefined (reading 'type')",
      "stack": "TypeError: Cannot read properties of undefined (reading 'type')\n    at isReadyForNewPregnancy (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:67821)\n    at 972 (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:69379)\n    at n (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76381)\n    at 344 (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:277)\n    at n (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76381)\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76492)\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:76500)\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:158)\n    at eval (eval at getGeneratorFunction (https://localhost/main.js:31384:36), <anonymous>:4:223)\n    at https://localhost/main.js:31432:27"
    },
    "meta": {
      "deviceId": "ab772fc1-2c00-4eb6-a34c-25487b76bf94",
      "language": "en",
      "source": "automatic",
      "time": "2026-02-24T06:54:38.137Z",
      "url": "https://localhost/#/contacts/9ecf55af-0eaa-41f9-bd4f-5949c0dc3f25",
      "user": {
        "name": "user1",
        "roles": [
          "chw"
        ]
      },
      "version": "5.0.0-local-development (~5.0.0)"
    },
    "type": "feedback"
  }
]
```

**Environment**
- Instance: local, CI
- Browser: Chrome latest
- App: webapp
- Version: 5.0.1

**Additional context**
This is an unlikely event. But we can protect against it. Ideally only real errors should be logged, not quick clicks throughout the app.

### PR DESCRIPTION
**Pull request by sh1vam31**
# Description

In the default configuration, clicking a contact immediately after a page refresh could cause a crash (e.g., TypeError: Cannot read properties of undefined (reading 'type') in isReadyForNewPregnancy). This happens because the contact summary calculation is triggered before the contact data has fully loaded.

Fixes #10661

## Root Cause
Several functions in contact-summary-extras.js were directly accessing thisContact.type without first verifying if this contact was defined.

## Fix
Added null checks (!thisContact ||) to the following functions in the default configuration:
isActivePregnancy
isReadyForNewPregnancy
isReadyForDelivery

These functions now safely return false if the contact is missing, preventing the crash and stopping unnecessary "Feedback" error reports from being created.

## Testing
Manual: Verified in local CHT instance by refreshing the "People" tab and clicking a contact as fast as possible. No crash occurred.
Automated: Added a new unit test suite config/default/test/contact-summary-extras/race_condition.spec.js
 that confirms handled undefined inputs.

# Code review checklist

- [ ] UI/UX backwards compatible: Test it works for the new design (enabled by default). And test it works in the old design, enable `can_view_old_navigation` permission to see the old design. Test it has appropriate design for RTL languages. 
- [x] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/)
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [x] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [x] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
- [x] AI disclosure: I used AI assistance to understand the issue and the codebase, then manually applied the fix and verified it works by running the unit tests locally.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by sh1vam31** [comment]
Hi @dianabarsan, @andrablaj, @sugat009

Kindly review the PR.
Please let me know if any changes or improvements are needed.

**Comment by sh1vam31** [comment]
Hey @dianabarsan,
You were right. I found the spot in the main application (contacts.effects.ts) where the race condition happens, and I fixed the root cause.

File: config/default/contact-summary-extras.js [hunk 1]
```diff
@@ -228,7 +228,7 @@ function getSubsequentPregnancies(allReports, refReport) {
 }
 
 function isActivePregnancy(thisContact, allReports, report) {
-  if (thisContact.type !== 'person' || !isAlive(thisContact) || !isPregnancyForm(report)) { return false; }
+  if (thisContact?.type !== 'person' || !isAlive(thisContact) || !isPregnancyForm(report)) { return false; }
```
Comment (dianabarsan) [inline config/default/contact-summary-extras.js]: I believe these changes are no longer necessary. Can you please revert them?

File: webapp/src/ts/effects/contacts.effects.ts [hunk 2]
```diff
@@ -210,8 +210,12 @@ export class ContactsEffects {
   private loadContactSummary(contactId, trackName) {
     const trackPerformance = this.performanceService.track();
     const selected = this.selectedContact;
-    return this.contactSummaryService
-      .get(selected.doc, selected.reports, selected.lineage, selected.targetDoc)
+    
+    const summaryPromise = selected?.doc
```
Comment (dianabarsan) [inline webapp/src/ts/effects/contacts.effects.ts]: This function got pretty hard to read with this addition. Resolving with undefined is a strange pattern. 

I think it should just be refactored, to use async await and stop execution if the contact gets deselected. We should not even track performance in this case, because it would just be incorrect, since the operation was effectively cancelled. Having these cancelled results in our performance could be enough to dilute the pool of metrics.

**Comment by sh1vam31** [comment]
Hi @dianabarsan, 

Thank you for the helpful review! I've just pushed a new commit addressing both of your points:

I reverted the optional chaining thisContact?.type changes in contact-summary-extras.js, returning it to its original state.
I refactored loadContactSummary in contacts.effects.ts to use async/await. It now safely returns early without starting the performance tracker if the document isn't loaded/selected yet, and if the operation gets cancelled mid-flight, it skips logging the performance metrics so we don't dilute the pool.

Let me know if everything looks good or if you need any further adjustments.

File: webapp/src/ts/effects/contacts.effects.ts [hunk 3]
```diff
@@ -207,25 +207,30 @@ export class ContactsEffects {
...
-            return this.contactsActions.updateSelectedContactSummary(summary);
-          });
-      })
-      .finally(() => {
-        trackPerformance?.stop({ name: [ ...trackName, 'load_contact_summary' ].join(':') });
-      });
+    let summary;
+
+    try {
+      if (selected?.doc) {
```
Comment (dianabarsan) [inline webapp/src/ts/effects/contacts.effects.ts]: I think we should somehow return early if there is no `selected.doc`, instead of going through all the after scripts. We should definitely not be tracking `load_contact_summary` if there is no selected contact.

**Comment by dianabarsan** [comment]
Thank you very much for the quick work on this @sh1vam31 ! I really appreciate it

**Comment by sh1vam31** [comment]
Hi @dianabarsan,
I've updated the fix based on your feedback!

I refactored loadContactSummary to include an early return if selected?.doc is missing. I also moved the performance tracking initialization below this check so that we no longer track load_contact_summary if no contact is selected.

Additionally, I've updated the unit tests in contacts.effects.spec.ts
 to include the doc property in the contact mocks, which ensures the tests now pass with all 7 performance tracks accounted for.

Thanks for your help

**Comment by sh1vam31** [comment]
Hi @dianabarsan,

I noticed that the ci-integration-all and ci-webdriver test suites are failing intermittently on this run (specifically, db-doc handler checks and stale element reference webdriver errors).

Since my changes on this branch were strictly limited to adding an early return in the frontend contacts.effects.ts
I believe these are known flaky tests related to the backend/CI environment rather than regressions from this PR.

I've re-run the failed jobs, but let me know if there's anything else I should look at.

File: webapp/src/ts/effects/contacts.effects.ts [hunk 4]
```diff
@@ -207,25 +207,34 @@ export class ContactsEffects {
...
+      this.contactsActions.updateSelectedContactSummary({ errorStack: error.stack });
+      trackPerformance?.stop({ name: [ ...trackName, 'load_contact_summary' ].join(':') });
+      throw error;
+    }
+
+    await this.verifySelectedContactNotChanged(contactId);
+
+    trackPerformance?.stop({ name: [ ...trackName, 'load_contact_summary' ].join(':') });
+    this.contactsActions.setContactsLoadingSummary(false);
+    return this.contactsActions.updateSelectedContactSummary(summary);
```
Comment (dianabarsan) [inline webapp/src/ts/effects/contacts.effects.ts]: I suppose that we could also use finally here, to avoid duplicating the trackPerformance.stop call: 
```suggestion
    try {
      summary = await this.contactSummaryService.get(
        selected.doc,
        selected.reports,
        selected.lineage,
        selected.targetDoc
      );
      await this.verifySelectedContactNotChanged(contactId);
       this.contactsActions.setContactsLoadingSummary(false);
      return this.contactsActions.updateSelectedContactSummary(summary);
          
    } catch (error) {
      this.contactsActions.updateSelectedContactSummary({ errorStack: error.stack });               
      throw error;
    } finally {
      trackPerformance?.stop({ name: [ ...trackName, 'load_contact_summary' ].join(':')});
    }
```

File: webapp/tests/karma/ts/effects/contacts.effects.spec.ts [hunk 5]
```diff
@@ -161,14 +161,14 @@ describe('Contacts effects', () => {
...
-      contactViewModelGeneratorService.getContact.resolves({ _id: 'contactid', model: 'contact model' });
+      contactViewModelGeneratorService.getContact.resolves({ _id: 'contactid', doc: {}, model: 'contact model' });
 
       await effects.selectContact.toPromise();
 
       expect(contactViewModelGeneratorService.getContact.callCount).to.equal(1);
       expect(contactViewModelGeneratorService.getContact.args[0]).to.deep.equal(['contactid', { merge: false }]);
       expect(setSelected.callCount).to.equal(1);
-      expect(setSelected.args[0]).to.deep.equal([{ _id: 'contactid', model: 'contact model' }]);
+      expect(setSelected.args[0]).to.deep.equal([{ _id: 'contactid', doc: {}, model: 'contact model' }]);
```
Comment (dianabarsan) [inline webapp/tests/karma/ts/effects/contacts.effects.spec.ts:171]: Can you please add a unit test that would demonstrate what happens when selected contact doc is not defined?

**Comment by sh1vam31** [comment]
Hi @dianabarsan,

Thank you for the feedback.

I have updated the PR with the following changes:

**Refactored loadContactSummary:** I've implemented the try/catch/finally block as suggested. trackPerformance.stop() is now in the finally block to ensure it always runs.

**Additional Unit Test:** I added a new test case in contacts.effects.spec.ts to verify that the application handles undefined contact documents gracefully without crashing, as requested.

**Regression Fix:** Note that I also added a check in the catch block to ensure we don't update the summary with an error state when the request is simply cancelled due to a contact change (SELECTED_CONTACT_CHANGED).

All tests are passing locally.

 Let me know if there's anything else needed.

File: couchdb/docker-entrypoint.sh [hunk 6]
```diff
@@ -34,19 +34,51 @@ setSecret() {
 	if [ -z "$COUCHDB_SECRET" ]; then
 		COUCHDB_SECRET=$(cat /proc/sys/kernel/random/uuid)
 	fi
-	# Set secret only if not already present
-	if ! grep -Pzq "\[couch_httpd_auth\]\nsecret =" $CLUSTER_CREDENTIALS; then
-		printf "\n[couch_httpd_auth]\nsecret = %s\n" "$COUCHDB_SECRET" >>$CLUSTER_CREDENTIALS
+	# Ensure [couch_httpd_auth] section exists
```
Comment (dianabarsan) [inline couchdb/docker-entrypoint.sh]: I believe these are part of a different work. Can you please remove them from this PR?

**Comment by sh1vam31** [comment]
Hi @dianabarsan, Thank you for the feedback! I've removed the unrelated changes in docker-entrypoint.sh and build.yml to ensure the PR is focused solely on the contact summary race condition fix.

File: .github/workflows/build.yml [hunk 7]
```diff
@@ -167,11 +167,11 @@ jobs:
         with:
           mask-password: 'true'
 
+      - uses: actions/checkout@v4
```
Comment (dianabarsan) [inline .github/workflows/build.yml:170]: I believe this change is unrelated.
