### PR TITLE
fix: prevent crash on rapid page switching in contacts detail

### LINKED ISSUE #10878: Switching pages too quickly can throw errors in the contacts detail page
**Describe the bug**
I logged in with a user with ~4000 docs + 1000 tasks (total 5176 docs). 
I loaded the reports page and triggered a search (which queried a fresh index), and then i switched to contacts and back to reports. I wasn't very quick and everything was manual. The app was busy indexing the search views. 

I thought indexing took too long so just checked the console randomly for errors, and found an unrelated error. 

**Expected behavior**
We should gracefully handle quick page switches, even at load. 

**Logs**
```
Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'doc')
TypeError: Cannot read properties of null (reading 'doc')
    at contacts-content.component.ts:293:46
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:17:1)
    at asyncToGenerator.js:22:1
    at new ZoneAwarePromise (zone.js:2221:23)
    at asyncToGenerator.js:14:1
    at ContactsContentComponent.updateFastActions (contacts-content.component.ts:299:8)
    at contacts-content.component.ts:354:14
    at xml-forms.service.ts:332:26
    at contacts-content.component.ts:293:46
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:17:1)
    at asyncToGenerator.js:22:1
    at new ZoneAwarePromise (zone.js:2221:23)
    at asyncToGenerator.js:14:1
    at ContactsContentComponent.updateFastActions (contacts-content.component.ts:299:8)
    at contacts-content.component.ts:354:14
    at xml-forms.service.ts:332:26
    at resolvePromise (zone.js:2018:21)
    at zone.js:1942:11
    at zone.js:1956:27
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _next (asyncToGenerator.js:17:1)
    at asyncToGenerator.js:22:1
    at new ZoneAwarePromise (zone.js:2221:23)
    at asyncToGenerator.js:14:1
    at ContactsContentComponent.updateFastActions (contacts-content.component.ts:299:8)
    at contacts-content.component.ts:354:14
```

**Screenshots**

Image

**Environment**
- Instance: local
- Browser: Chrome
- App: webapp
- Version: latest `master`

### PR DESCRIPTION
**Pull request by sh1vam31**
# Description

### Fixes #10878
This PR fixes a `TypeError: Cannot read properties of null (reading 'doc')` in the Contacts Detail page that occurs when a user navigates between pages very quickly.

## Problem
The crash was caused by a race condition: when a user switches pages quickly, the Redux store clears the `selectedContact` (setting it to `null`). However, asynchronous callbacks or pending emissions from `XmlFormsService` and other background tasks were still executing and attempting to access properties like `.doc` on the now-null contact.

## Changes
- **Defensive Null Checks**: Added optional chaining (`?.`) throughout the `ContactsContentComponent` when accessing `selectedContact`.
- **Early Returns**: Implemented early returns at the beginning of `updateFastActions()` and within the subscription callbacks for `xmlFormsService`. If the component state has been cleared by navigation, these methods now exit gracefully instead of attempting to access null properties.

# Code review checklist

- [ ] UI/UX backwards compatible: Test it works for the new design (enabled by default). And test it works in the old design, enable `can_view_old_navigation` permission to see the old design. Test it has appropriate design for RTL languages. 
- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/)
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
- [ ] AI disclosure: Please disclose use of AI per [the guidelines](https://docs.communityhealthtoolkit.org/community/contributing/ai-guidelines/).

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by sh1vam31** [comment]
Hello @dianabarsan,

I've submitted this PR to address issue #10878 regarding the crash in the Contacts Detail page.

Changes included:

**UI Bug Fix:** Added defensive null guards and early returns in ContactsContentComponent to prevent TypeError when navigating away from a contact quickly while asynchronous background tasks are still running.

**Test Stabilisation:** During local testing, I noticed some flakiness in the sentinel/audit.spec.js integration tests due to a race condition with asynchronous audit log generation. I've added waitForAuditCount and waitForAuditDocs polling helpers to tests/utils/index.js and updated the audit tests to use them.

I have verified the webapp changes with npm run lint and the integration tests locally with Docker. Both are passing and should be much more stable now.

Looking forward to your feedback!

File: tests/utils/index.js [hunk 1]
```diff
@@ -1101,6 +1101,30 @@ const waitForDocRev = (ids) => {
   });
 };
 
+const waitForAuditCount = async (docId, expectedCount) => {
```
Comment (dianabarsan) [inline tests/utils/index.js]: it looks like this is an unrelated change. I've noticed a lot of these bleeding through your PRs. to avoid pointless review change requests, can you please make sure you don't include unrelated changes in your PRs? Thanks!

**Review by dianabarsan — CHANGES_REQUESTED** [review]
I think the changes look good. can you please add some unit testing around them?

**Comment by sh1vam31** [comment]
Hi @dianabarsan,

Thank you for the feedback.

I have now added unit tests to verify the defensive null-checks in ContactsContentComponent. I also refactored the anonymous subscription callbacks into named private methods to make them testable and improve readability.

Additionally, I have reverted the unrelated audit test changes to ensure this PR remains strictly focused on handling quick page switches.

Thanks for your patience and for helping keep the codebase clean.

**Review by dianabarsan — APPROVED** [review]
Awesome!!
