### PR TITLE
fix(#10444): add retry fetching purged docs cache

### LINKED ISSUE #10444: Reading purged docs cache fails sometimes when the number of purged docs for a user is very large
**Describe the bug**
HAproxy can respond with an invalid body when trying to read a doc of large size (apparently). Purged cache docs have the potential of becoming large, however reading large json documents should be supported. 

**To Reproduce**
1. Create a user with 50.000 docs
2. Purge 40.000 of these docs
3. Try to replicate with this user
4. Check error. 

**Expected behavior**
Replication should succeed

**Logs**
```
2025-11-05T17:28:14.018 ERROR: Server error: FetchError: Invalid response body while trying to fetch http://haproxy:5984/medic-purged-cache/purged-docs-<username>: read ECONNRESET
    at PassThrough.<anonymous> (/service/api/node_modules/node-fetch/lib/index.js:400:12)
    at PassThrough.emit (node:events:530:35)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  message: 'Invalid response body while trying to fetch http://haproxy:5984/medic-purged-cache/purged-docs-<username>: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  [stack]: [Getter/Setter],
  docId: 'purged-docs-<username>',
  name: 'FetchError'
} 
2025-11-05T17:28:14.019 RES: 09f1537d4c11 196.96.136.145 - GET /api/v1/replication/get-ids HTTP/1.0 500 - 1203667.116 ms
```

However haproxy reports the same request as successful: 
```
<150>Nov  5 17:28:14 haproxy[12]: 172.18.0.2,couchdb,200,340663,162,0,GET,/medic-purged-cache/purged-docs-<username>,api,medic,09f1537d4c11,2603727,35,2874667,'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)'
```

For reference, this user had ~30.000 cached docs and the size of the cache document is ~400kB. 

**Environment**
- Instance: production
- App: api
- Version: 4.21

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

closes #10444

# Code review checklist

- [ ] UI/UX backwards compatible: Test it works for the new design (enabled by default). And test it works in the old design, enable `can_view_old_navigation` permission to see the old design. Test it has appropriate design for RTL languages. 
- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10444-retry-fetching-purged-docs-cache/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10444-retry-fetching-purged-docs-cache/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10444-retry-fetching-purged-docs-cache/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
I haven't been able to reproduce this issue, so I added a retry. It could have been some weird inter-container communication issue or delays that had nothing to do with the CHT.

File: api/src/services/purged-docs-cache.js [hunk 1]
```diff
@@ -48,12 +43,23 @@ const wipe = async () => {
...
+
+const getCacheDoc = async (username, retry = 3) => {
   try {
     const database = await getCacheDatabase();
     return await database.get(getCacheDocId(username));
   } catch (err) {
-    catchDocNotFoundError(err);
+    if (err?.code === ECONNRESET && retry > 0) {
+      logger.warn('Retrying getCacheDoc for user %s after ECONNRESET', username);
+      return await getCacheDoc(username, --retry);
```
Comment (jkuester) [inline api/src/services/purged-docs-cache.js:62]: No need to make any changes, but the one thing I did think of while looking at this was if it would be good to add a timeout before the retry? 🤔   

I get that we cannot wait too long, but I guess if the DB is overloaded, it _might_ help to wait a bit... 🤷

**Review by jkuester — APPROVED** [review]
Too bad that we don't have a reliable repro, but I don't see how retrying the failed request is going to hurt anything... 😅 

LGTM!

File: api/src/services/purged-docs-cache.js (hunk 1 above)
Comment (dianabarsan) [reply api/src/services/purged-docs-cache.js:62]: Good point. I'll add a short timeout.
