### PR TITLE
Fix #923 and #919 - bugs when deleting contacts

### LINKED ISSUE #919: After deleting a contact, a page reload is needed for the contact to disappear from the left pane
See screenshot below. After deleting a contact, the contact details disappear from the right pane, but the contact remains in the left pane. I'd expect it to disappear from both.

delete-1

After a page reload, it becomes apparent that the contact is indeed gone.

### LINKED ISSUE #923: Contacts: Deleting a person immediately raises an "Error fetching contacts" exception
Using the demo dataset, deleting `Yuko Yarnall` – or any other person – immediately raises an error and throws two exception/backtrace messages up on the console. Screenshot:

contacts-1

Here are the backtraces in text form:

```
"Error fetching parents" Error: null
Stack trace:
[79]</</</</<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:67:7945
o/n.error/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:9165
i@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:25812
j/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:25984
Vb/this.$get</l.prototype.$eval@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1099
Vb/this.$get</l.prototype.$digest@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:31612
Vb/this.$get</l.prototype.$evalAsync/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1188
g@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:2:19515
Va/n.defer/c<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:2:21596
 inbox.js:47:24911
"Error searching for contacts" Error: null
Stack trace:
[99]</</</</</<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:67:25761
o/n.error/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:9165
i@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:25812
j/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:25984
Vb/this.$get</l.prototype.$eval@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1099
Vb/this.$get</l.prototype.$digest@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:4:31612
Vb/this.$get</l.prototype.$evalAsync/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1188
g@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:2:19515
Va/n.defer/c<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:2:21596
```

### PR DESCRIPTION
**Pull request by alxndrsn**
This changes the behaviours of the `ContactUdpated` listeners in various
controllers to simplify their handling of deleted contacts.  In short,
the listeners update `$scope.items` directly, where appropriate, in
place of triggering database queries.

This should fix #919 and #923.

@garethbowen please review!

### CODE REVIEW

File: static/js/controllers/inbox.js [hunk 1]
```diff
@@ -148,6 +148,16 @@ require('moment/locales');
         $scope.items = contacts || [];
       };
 
+      $scope.removeContact = function(contact) {
```
Comment (alxndrsn) [inline static/js/controllers/inbox.js]: I had a reason for putting the method in this particular controller, but I'm not sure if it's a good reason... there is another method in `inbox.js` called `removeDeletedContacts()`, which I initially tried to call to do the dirty work for me.  Sadly it didn't really work.  If there is a more suitable place for this function to go (e.g. in `ContactsCtrl`) then I will happily move it.

**Comment by alxndrsn** [comment]
Please hold off reviewing - have to fix some little merge problems...

**Comment by alxndrsn** [comment]
I think this is "good" now.  But there is one slight problem - it's not possible to delete a contact whose Catchment Area has already been deleted separately.  This happens on `develop` for me as well though, so perhaps this PR is still an improvement!

File: static/js/controllers/contacts-content.js [hunk 2]
```diff
@@ -11,11 +11,12 @@
       $scope.selectContact($stateParams.id);
 
       $scope.$on('ContactUpdated', function(e, contact) {
-        if (!contact || (
-            contact._deleted &&
-            $scope.selected &&
-            $scope.selected._id === contact._id)) {
+        if (!contact) {
```
Comment (alxndrsn) [inline static/js/controllers/contacts-content.js]: It looks like when `contact == null`, we are dealing with data imports.

File: static/js/controllers/edit-contact.js [hunk 3]
```diff
@@ -53,7 +53,13 @@ var libphonenumber = require('libphonenumber/utils'),
...
       populateParents();
 
-      $scope.$on('ContactUpdated', populateParents);
+      $scope.$on('ContactUpdated', function(e, contact) {
+        if (contact && contact._deleted) {
+          // allow the ContactCtrl to handle contact deletion
+          return;
+        }
+        populateParents();
+      });
```
Comment (garethbowen) [inline static/js/controllers/edit-contact.js]: This will leave the EditContact modal in an inconsistent state - ie: it will still have old deleted contacts in the parent dropdown.

Because the EditContact modal is in the root context I think it should be allowed to complete even if navigation occurs, so see if you can set `timeout:false` on this request.

File: static/js/controllers/inbox.js [hunk 4]
```diff
@@ -148,6 +148,16 @@ require('moment/locales');
...
+        var i, id = contact._id;
+        for (i=$scope.items.length-1; i>=0; --i) {
+          if($scope.items[i]._id === id) {
+            $scope.items.splice(i, 1);
+            return;
+          }
+        }
+      };
+
```
Comment (garethbowen) [inline static/js/controllers/inbox.js]: Consider using the underscore.js library here to make this more readable. _.reject or _.findIndex (if you upgrade to 1.8).

File: static/js/controllers/inbox.js [hunk 5]
```diff
@@ -202,7 +212,11 @@ require('moment/locales');
         });
       };
 
-      $scope.$on('ContactUpdated', function() {
+      $scope.$on('ContactUpdated', function(contact) {
+        if (!contact || contact._deleted) {
+          // allow the ContactCtrl to handle contact deletion
+          return;
+        }
```
Comment (garethbowen) [inline static/js/controllers/inbox.js]: This will leave the Facilities filter in an inconsistent state - ie: you'll be able to filter for facilities that no longer exist. As above, because this is in the root you should be able to safely allow the request to finish with timeout:false

File: static/js/controllers/inbox.js (hunk 1 above)
Comment (garethbowen) [inline static/js/controllers/inbox.js]: That "removeDeletedContacts" method is historically named, but is actually for updating Messages not Contacts. Please refactor it and "mergeUpdatedContacts" to "removeDeletedMessages" and "mergeUpdatedMessages" respectively.

Comment (garethbowen) [inline static/js/controllers/inbox.js]: Always attempt to put methods as far down the hierarchy as possible, so give ContactsCtrl a try. The catch is if you set a variable it'll change in the copy attached to the $scope of ContactsCtrl, not InboxCtrl. For example, `$scope.items = []` wouldn't update the parent scope. This is why we have setters in InboxCtrl - so the child controllers can update the parent scope. Splice should be fine, but it's something to keep an eye on.

File: static/js/controllers/contacts-content.js (hunk 2 above)
Comment (garethbowen) [inline static/js/controllers/contacts-content.js]: If importing fired its own event we'd have to listen for that event in all the same places we listen for the current one. For me it makes much more sense to have one event and pass parameters to distinguish between the update types. Maybe we should change the param from a Contact to a list of Contacts, then this function can pass through all the contacts that were imported, and listeners who care can iterate through the list.

File: static/js/controllers/inbox.js (hunk 5 above)
Comment (alxndrsn) [inline static/js/controllers/inbox.js]: I will try to prevent timeout.
Is there some provision for two deletes happening in quick succession, and the resulting updates returning in the wrong order?

File: static/js/controllers/contacts-content.js (hunk 2 above)
Comment (alxndrsn) [inline static/js/controllers/contacts-content.js]: Seems fine.  I wouldn't add the list of contacts until we actually see a need for that though.
I guess it's the event's name which misled me - I guess it's more literally `Contact(s)Updated`.  Not suggesting we change it, though!

File: static/js/controllers/inbox.js (hunk 5 above)
Comment (garethbowen) [inline static/js/controllers/inbox.js]: Sure a small window. We could implement a request cancellation system where if a request is made through the HttpWrapper which is identical to one already sent then the first one gets cancelled? Low priority as it's unlikely to happen often.

File: static/js/controllers/contacts-content.js (hunk 2 above)
Comment (garethbowen) [inline static/js/controllers/contacts-content.js]: "OneOrMoreContactsWereUpdatedOrInsertedOrDeleted"?

File: static/js/controllers/inbox.js (hunk 1 above)
Comment (alxndrsn) [inline static/js/controllers/inbox.js]: Ref renaming `*DeletedContacts` to `*DeletedMessages`, should I also look at why the messages are stored in a variable called `options.contacts`?!

Comment (garethbowen) [inline static/js/controllers/inbox.js]: Yeah also good to change `options.contacts`. This all dates back to the original screens where Messages were called Contacts (before the new Contacts existed).

File: static/js/controllers/inbox.js (hunk 5 above)
Comment (alxndrsn) [inline static/js/controllers/inbox.js]: Yep, feels v. low priority, unless end users likely to see significant failure rates or inconsistent response times with their Ajax requests.

File: static/js/controllers/contacts-content.js (hunk 2 above)
Comment (alxndrsn) [inline static/js/controllers/contacts-content.js]: `OrMaybeItWasALocationOfSomeSort;-)`

File: static/js/controllers/inbox.js (hunk 5 above)
Comment (alxndrsn) [inline static/js/controllers/inbox.js]: Happy to roll this back, and add `timeout: false` for the facilities request.  But I can't make the current `develop` branch behave properly for this anyway when a contact is deleted, so it's very hard for me to tell whether things are getting better or not.
N.B. allowing `$scope.updateAvailableFacilities();` does not throw an exception even without `timeout: false`

File: static/js/controllers/inbox.js (hunk 1 above)
Comment (alxndrsn) [inline static/js/controllers/inbox.js]: N.B. I made the renames on `develop` and then rebased this PR onto latest `develop`

Comment (alxndrsn) [inline static/js/controllers/inbox.js]: If the children should be able to update the parents' scope, why are they scoped separately?

Comment (alxndrsn) [inline static/js/controllers/inbox.js]: Moving `removeContact` to be a method within `ContactsCtrl` seems to work, even if it's assigning `$scope.items`.  I will push this change, but please check if I'm missing something and it's not working as it should.

File: static/js/controllers/contacts-content.js [hunk 6]
```diff
@@ -11,11 +11,12 @@
...
           $scope.select();
+        } else if(contact._deleted &&
+            $scope.selected &&
+            $scope.selected._id === contact._id) {
+          $scope.selected = null;
```
Comment (garethbowen) [inline static/js/controllers/contacts-content.js]: I think you need to call $scope.setSelected() here. Firstly setSelected() does more work such as scrolling the list pane into view in the mobile view. Secondly, you're setting selected on the $scope attached ContactsContentCtrl not the one in the InboxCtrl. This may cause unexpected results.
