### PR TITLE
fix(#10621): use default page size for freetext searching

### LINKED ISSUE #10621: Free text search downloads all search results even if only 50 are displayed
**Describe the bug**
Simple freetext search seems to get all results for the search for every search "page" instead of getting one page at a time. 

**To Reproduce**
1. Have a large instance. your search term should yield more than 100 results.
2. Make a report freetext search - don't use other filters. 
3. It takes a long time to load the results. 
4. Scrolling to the next results page takes equal amount of time. 
5. Inspecting the console, you see many ajax requests to the server. 

**Expected behavior**
A single request should be made for one page of results. 

**Video**
https://github.com/user-attachments/assets/d1c0227a-55fd-45d5-a686-afa4c10330d9

**Environment**
- App: webapp
- Version: 5.0.0

### PR DESCRIPTION
**Pull request by jkuester**
# Description

Updates the paged generator logic in cht-datasource (used in the freetext searching) to not hard-code the page limit to `100`. Instead it should use the _default_ page limit for the given paging function.  This means that when paging with a generator we should use the defaults from the [contants file](https://github.com/medic/cht-core/blob/4d3c72f61a17d761f76bf6efbef3d13bf619f491/shared-libs/cht-datasource/src/libs/constants.ts).  (`100` per page _for docs_ and `10000` per page _for uuids_).  

Closes #10621

### AI Disclosure

Quite a bit of the updated unit test code was at least partially written by Claude. For other parts of the logic I consulted with Claude on some things, but the actual code changes were handmade... 

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Tested: Unit and/or e2e where appropriate
- [X] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

File: shared-libs/cht-datasource/src/libs/core.ts [hunk 1]
```diff
@@ -130,26 +130,18 @@ export interface Page<T> {
...
-  let docs: Page<T>;
-  const getDocsDataLength = (docs: Page<T>) => docs.data.length;
-
+  let currentCursor: Nullable<string> = null;
   do {
-    docs = await fetchFunction(fetchFunctionArgs, cursor, limit);
-
-    for (const doc of docs.data) {
-      yield doc;
+    const { data, cursor } = await fetchFunction(fetchFunctionArgs, currentCursor);
```
Comment (jkuester) [inline shared-libs/cht-datasource/src/libs/core.ts:138]: Calling this function without the hardcoded `limit` of 100 is the key change here.  This lets the code fall back on the default limits for each particular function (so we end up using `100` when fetching docs and `10000` when fetching uuids).

File: shared-libs/cht-datasource/src/libs/core.ts [hunk 2]
```diff
@@ -130,26 +130,18 @@ export interface Page<T> {
...
+    for (const entry of data) {
+      yield entry;
     }
 
-    cursor = docs.cursor;
-    // 1. W10= is the base64 representation of an empty array which is returned by Nouveau which will evaluate to '[]'
-    // 2. This check was changed because in online mode(querying Nouveau) the cursor returned can be not W10= so to
-    //    prevent infinite querying the check for existence of docs was required
-  } while (getDocsDataLength(docs) > 0 && cursor && atob(cursor) !== '[]');
```
Comment (jkuester) [inline shared-libs/cht-datasource/src/libs/core.ts:152]: I simplified this by updating the logic for returning the cursor in `src/local/libs/nouveau.ts`.  Basically, when you reach the last page of a Nouveau query (and there are no more results) the Couch request will return [a duplicate `bookmark` value](https://docs.couchdb.org/en/stable/api/ddoc/nouveau.html#get--db-_design-ddoc-_nouveau-index).  So we can check that and set a `null` cursor and avoid an extra request without needing this extra logic.

File: shared-libs/cht-datasource/src/local/libs/constants.ts
Comment (jkuester) [inline shared-libs/cht-datasource/src/local/libs/constants.ts:1]: Just moved this logic into nouveau.ts since it does not really need to be reused anywhere else.

File: shared-libs/cht-datasource/src/local/libs/data-context.ts
Comment (jkuester) [inline shared-libs/cht-datasource/src/local/libs/data-context.ts:1]: This function actually needs to be very specific to Nouveau (since it really should not be used to check if the current user is offline or something).  It is just to determine if we need to use the Nouveau endpoints or not (because Pouch does not encapsulate this for us).  So, I also moved this to the nouveau.ts file.

**Comment by jkuester** [comment]
Okay, @sugat009 this should be good to review!  The actual fix here was pretty simple, but it seemed like a bunch of complexity from `shared-libs/search` had leaked into the cht-datasource nouveau code. I think I was able to simplify things quite a bit, but look closely in case I accidentally broke some functionality I did not understand... :cold_sweat: 

Also note that these changes are not intended to change the behavior where we re-fetch _all search result UUIDs_ for each page and the user scrolls through the pages in the app.  I have logged a separate enhancement for that work: https://github.com/medic/cht-core/issues/10625 (I do not think it needs to be addressed before the pending releases.)

**Review by sugat009 — APPROVED** [review]

**Comment by sugat009** [comment]
Tested in browser for contacts and reports along with API.

1. For contacts search:

Image

2. For reports search:

Image

3. For contacts API:
    1. For more less data than limit:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/contact/uuid?limit=10000&freetext=house" | jq '{total: (.data | length), cursor: .cursor}'
        {
          "total": 1450,
          "cursor": null
        }
        ```
    
    2. For exact number of items as limit:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/contact/uuid?limit=1450&freetext=house" | jq '{total: (.data | length), cursor: .cursor}'
        {
          "total": 1450,
          "cursor": "W1t7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3aW5kbGVyZm9ydCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImQzZDA5OTdlLWUyNzgtNGFjOS05ZTY0LThlMTVkNjk1MWU3MSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3aXR0aW5nbGFuZCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImM4Y2FkN2RkLWFjMjUtNDU0Ny04NTcwLWJlMjk0MWNkMjQ4MiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB6dWxhdWZidXJnaCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImNmZDNiMDkxLWQxZTktNDlhNS04OTU4LThiNDdmZjRlNTA4MiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB5b3N0bGFuZCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6Ijg4Mjc2MTNjLTQzNmMtNDFhNC1iNDJkLTU0N2Q2YjY4NjBjMyIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB6dWxhdWZtb3V0aCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImMyOTM2Njg1LTY0YWQtNDNhZi1hOTQ5LWFmYWM4YWM4NGM0OCIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3b29kYnVyeSdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjFiOWNjODQ0LWJjZmUtNGEwMC05ZTY1LWVlY2QwYTJjNjUzMyIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB5b25rZXJzJ3MgaG91c2Vob2xkIiwiQHR5cGUiOiJzdHJpbmcifSx7InZhbHVlIjoiNjU0N2NiMjMtZDY2MC00ZWY2LWEzZDQtZGIxNzM5ODVhZjY5IiwiQHR5cGUiOiJzdHJpbmcifV0sW3sidmFsdWUiOiJmYWxzZSBmYWxzZSAyIHplbWxha3NpZGUncyBob3VzZWhvbGQiLCJAdHlwZSI6InN0cmluZyJ9LHsidmFsdWUiOiIxOWE5MmI5MC1kNWY1LTRjNWYtOGRlZi04Y2FjNGQ5NzQxMWMiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6ImZhbHNlIGZhbHNlIDIgeW9zdGJvcm91Z2gncyBob3VzZWhvbGQiLCJAdHlwZSI6InN0cmluZyJ9LHsidmFsdWUiOiIxZDMzMjA4Mi05ZWE2LTQ3NTktYTVhZC03YjNiZTg2NDdmZjQiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6ImZhbHNlIGZhbHNlIDIgemVsbGFoYXZlbidzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjNkNWU1MGQ0LWYzYmItNDg2MC04ZjRlLTgzM2UxNjAyMTI4ZSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3dWNrZXJ0YmVyZydzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjUxZjYwYmZiLTkzZWItNGY5Ni1iNWNkLThiYmNkN2I5NDM1MiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB6dWxhdWZzaWRlJ3MgaG91c2Vob2xkIiwiQHR5cGUiOiJzdHJpbmcifSx7InZhbHVlIjoiNTMzMjk5NWMtOTQ2OC00NjdhLTg4ZTEtNDU5YjdiNGFhOWIyIiwiQHR5cGUiOiJzdHJpbmcifV1d"
        }
        ```

    3. For (n-1) limit as number of items:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/contact/uuid?limit=1449&freetext=house" | jq '{total: (.data | length), cursor: .cursor}'
        {
          "total": 1449,
          "cursor": "W1t7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3aW5kbGVyZm9ydCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImQzZDA5OTdlLWUyNzgtNGFjOS05ZTY0LThlMTVkNjk1MWU3MSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3aXR0aW5nbGFuZCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImM4Y2FkN2RkLWFjMjUtNDU0Ny04NTcwLWJlMjk0MWNkMjQ4MiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB6dWxhdWZidXJnaCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImNmZDNiMDkxLWQxZTktNDlhNS04OTU4LThiNDdmZjRlNTA4MiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB5b3N0bGFuZCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6Ijg4Mjc2MTNjLTQzNmMtNDFhNC1iNDJkLTU0N2Q2YjY4NjBjMyIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB6dWxhdWZtb3V0aCdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6ImMyOTM2Njg1LTY0YWQtNDNhZi1hOTQ5LWFmYWM4YWM4NGM0OCIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3b29kYnVyeSdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjFiOWNjODQ0LWJjZmUtNGEwMC05ZTY1LWVlY2QwYTJjNjUzMyIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB5b25rZXJzJ3MgaG91c2Vob2xkIiwiQHR5cGUiOiJzdHJpbmcifSx7InZhbHVlIjoiNjU0N2NiMjMtZDY2MC00ZWY2LWEzZDQtZGIxNzM5ODVhZjY5IiwiQHR5cGUiOiJzdHJpbmcifV0sW3sidmFsdWUiOiJmYWxzZSBmYWxzZSAyIHplbWxha3NpZGUncyBob3VzZWhvbGQiLCJAdHlwZSI6InN0cmluZyJ9LHsidmFsdWUiOiIxOWE5MmI5MC1kNWY1LTRjNWYtOGRlZi04Y2FjNGQ5NzQxMWMiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6ImZhbHNlIGZhbHNlIDIgeW9zdGJvcm91Z2gncyBob3VzZWhvbGQiLCJAdHlwZSI6InN0cmluZyJ9LHsidmFsdWUiOiIxZDMzMjA4Mi05ZWE2LTQ3NTktYTVhZC03YjNiZTg2NDdmZjQiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6ImZhbHNlIGZhbHNlIDIgemVsbGFoYXZlbidzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjNkNWU1MGQ0LWYzYmItNDg2MC04ZjRlLTgzM2UxNjAyMTI4ZSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3dWNrZXJ0YmVyZydzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjUxZjYwYmZiLTkzZWItNGY5Ni1iNWNkLThiYmNkN2I5NDM1MiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoiZmFsc2UgZmFsc2UgMiB3aXNvemtzaGlyZSdzIGhvdXNlaG9sZCIsIkB0eXBlIjoic3RyaW5nIn0seyJ2YWx1ZSI6IjRjM2MxNWEyLWJhNzAtNDAwYS1hMGM2LWMyNTE4NmRkM2FjYyIsIkB0eXBlIjoic3RyaW5nIn1dXQ"
        }
        ```

    4. For (n + 1) limit as number of items:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/contact/uuid?limit=1451&freetext=house" | jq '{total: (.data | length), cursor: .cursor}'
        {
          "total": 1450,
          "cursor": null
        }
        ```

4. For reports API:
    1. Limit < number of items:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/report/uuid?limit=10000&freetext=pregnancy" | jq '{total: (.data | length), cursor: .cursor}'

        {
          "total": 10000,
          "cursor": "W1t7InZhbHVlIjoxNzU5NjYzNDAwMDE1LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjIyN2RkNzNhLTM3ZDItNGFmOS1hOGZjLTdjZWJkYjMyYTljYSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzk1ODc1LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjZiNTUwZTQ3LWRlODItNDdjNi05NjRjLTE0NWIxZmNmZWMyMSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzkzNDU1LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6ImY2ZTc4N2NlLTUxNDctNDcyZi05NWNlLTVmNWUxZTMyMmQzYiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzYzOTk4LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjZkOWRkNzczLTc1YmEtNGIwMy05NjExLWY2YzM0Mjc5YTU2MSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzc4OTgyLjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6ImFiYWE2YjA5LTgzZjMtNDcwYy1hNGRjLTBiMTQ0YmRkMzFjYiIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzk4NjQ1LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjkyMmQ1OWRmLWMyZDktNDdhYi04YTVhLWY3MmIyMzQ0ZGVmNCIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzNDAxNDUyLjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjQ5ZmQ4N2JjLTY4ZTItNGM1Ni1iZDQ2LTdmYjkyYmMwYzE1MSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzk4MjU1LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjA2MWU5Yjc0LTFhMDItNGM4Ny1hOWVhLTJjZjEyOGIzYjc5YSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzNDAyMjM0LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6ImM1MWY4MmUyLWVlZDMtNDFkMS05MmFhLWE3MDMyZWFhZjZmMSIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzk1ODU0LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjIxNDFkNTUzLWNhOWItNGM1My05YTY5LTZjNDdkYzdjYmYwNCIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzgxOTU3LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjQyNGY1NzJjLTFhZGEtNGQyNy1iNjhhLTY5MTRiMTMyNTdlYyIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzU5NjYzMzk2OTE3LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjNiODM5YWFkLWUzMWMtNDVlNS1hMDI5LWRlY2YyZWY0NjhiYyIsIkB0eXBlIjoic3RyaW5nIn1dXQ"
        }
        ```
    2. Limit > number of items:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/report/uuid?limit=999999&freetext=pregnancy" | jq '{total: (.data | length), cursor: .cursor}'

        {
          "total": 530011,
          "cursor": null
        }

        ```
    3. Limit = number of items:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/report/uuid?limit=530011&freetext=pregnancy" | jq '{total: (.data | length), cursor: .cursor}'

        {
          "total": 530011,
          "cursor": "W1t7InZhbHVlIjoxNzYwMDg3NDY2NTc0LjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6ImJhNDcyMjI3LTQ3NTAtNDJmOC1hY2Y0LWRkNzkyZWY5MGJkMCIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzYxOTMwMDMyMDAwLjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjVmMTMxY2FjMjU3ZDUyMzZhNDhiMGEwMjcxMDBhN2UyIiwiQHR5cGUiOiJzdHJpbmcifV0sW3sidmFsdWUiOjE3NjE5MzA2NDIwMDAuMCwiQHR5cGUiOiJkb3VibGUifSx7InZhbHVlIjoiNWYxMzFjYWMyNTdkNTIzNmE0OGIwYTAyNzEwMGFiMzEiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MDA4NzM4MDcwOC4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiIzZmJjZmM4Yy02NmM2LTQxNDgtODA3Mi05Y2E3MzI5MzNlNWUiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MDA4NzQ4NDQzOC4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiJkZWE3ZGRiZS1jZDI4LTRiNzgtOTEyZC00YTk4ZTU0NThkMTUiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MDA4NzQ4MTUwMy4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiIwMGM5YzVlYi1mNzdiLTRiZWQtODIwNy05MmU1NjFjNGI2MjkiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MDA4NzQ5ODk3NC4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiJjOWQwOTMxOC04ZWIwLTQ5MDQtYTg3Ni00M2MwMmZiNzJkNzEiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MTk4MTc1OTAwMC4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiI2NGU5MDM5MTIxMzZjZThmOTJhNTk2Mjg2NTAwMTdmOCIsIkB0eXBlIjoic3RyaW5nIn1dLFt7InZhbHVlIjoxNzYxOTgxNzU5MDAwLjAsIkB0eXBlIjoiZG91YmxlIn0seyJ2YWx1ZSI6IjY0ZTkwMzkxMjEzNmNlOGY5MmE1OTYyODY1MDAwZjgyIiwiQHR5cGUiOiJzdHJpbmcifV0sW3sidmFsdWUiOjE3NjE5MzAwMzIwMDAuMCwiQHR5cGUiOiJkb3VibGUifSx7InZhbHVlIjoiNWYxMzFjYWMyNTdkNTIzNmE0OGIwYTAyNzEwMGEzZWEiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MDA4NzQ0ODgxMS4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiI3OWJkMGFjOS03ZDFhLTRmZDEtODRiOS0zOGE3M2NmMjliYWQiLCJAdHlwZSI6InN0cmluZyJ9XSxbeyJ2YWx1ZSI6MTc2MDA4NzQ1MTkwNS4wLCJAdHlwZSI6ImRvdWJsZSJ9LHsidmFsdWUiOiIxZjAwOGEyNS05ZTE0LTQzNzMtYWRmZC1kNDJhNWNkZTVmMmIiLCJAdHlwZSI6InN0cmluZyJ9XV0"
        }
        ```
    4. Limit + 1 = number of items:
        ```bash
        curl -s -u medic:password "http://localhost:5988/api/v1/report/uuid?limit=530012&freetext=pregnancy" | jq '{total: (.data | length), cursor: .cursor}'

        {
          "total": 530011,
          "cursor": null
        }
        ```

5. Contact type + freetext combied
    1. Limit > number of items
    ```bash
    curl -s -u medic:password "http://localhost:5988/api/v1/contact/uuid?limit=10000&contactType=person&freetext=house" | jq '{total: (.data | length), cursor: .cursor}'

    {
      "total": 1450,
      "cursor": null
    }
    ```
    2. Limit < number of items
    ```bash
    curl -s -u medic:password "http://localhost:5988/api/v1/contact/uuid?limit=1449&freetext=house" | jq '{total: (.data | length), cursor_is_null: (.cursor == null)}'

    {
      "total": 1449,
      "cursor_is_null": false
    }
    ```

_On a sidenote, also discovered that the nouveau endpoints have a limit of ~3.5MB response limit. I put limit as 10,00,000 instead of 10,000 just for testing and the nouveau endpoint was throwing a `500`. The limit for our contacts and reports uuid endpoints would round up  around `3670020` but this is way above our `10000` default limit. Since the API allows passing custom limit values, we may want to consider adding validation or documenting this constraint._

**Comment by jkuester** [comment]
Thanks for the testing! :heart: 

> also discovered that the nouveau endpoints have a limit of ~3.5MB response limit. I put limit as 10,00,000 instead of 10,000 just for testing and the nouveau endpoint was throwing a 500

Interesting! :thinking: Getting a 500 back for too high of a limit is probably not the worst API experience, but having a max limit would be a good idea just to protect the server from excessively heavy calls.  :+1:
