### PR TITLE
fix(#10802): check status before a message is processed

### LINKED ISSUE #10802: Message getting sent to pending state even after it is sent.
A message is getting sent to pending state even after it is already sent to the same user. 

**Describe the bug**
Already sent messages are sent repeatedly (up to every 5 minutes, for up to 7 days) when a document has two scheduled_tasks with the same due date and one of them is stuck in scheduled state. This was seen in some of the instances randomly. Now, the issue has been occuring more frequently causing CHT to send up to 1900 SMS messages over period of 7 days. 

This means a single patient can receive the same SMS message up to ~2,016 times (7 days × 24 hours × 60 min / 5 min) in the worst case.

**Expected behavior**
Once the task is processed, it should no longer be sent to pending queue regardless of the state of other tasks. Process tasks in current window that are only in `scheduled` state. 

**Environment**
- Instance: All
- Browser: Any
- Client platform: Any
- App: webapp, sentinel
- Version: 4.22.0, 5.1.0, known to have existed on all 3.x versions as well

**Additional context*
I've posted detail on this in medic/config-lumbini/issues/221 (private repo).

### PR DESCRIPTION
**Pull request by 1yuv**
# Description

Fix #10802 

# Code review checklist

- [ ] UI/UX backwards compatible: Test it works for the new design (enabled by default). And test it works in the old design, enable `can_view_old_navigation` permission to see the old design. Test it has appropriate design for RTL languages. 
- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/)
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
- [ ] AI disclosure: Please disclose use of AI per [the guidelines](https://docs.communityhealthtoolkit.org/community/contributing/ai-guidelines/).

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10802_scheduling_fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10802_scheduling_fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10802_scheduling_fix/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

File: shared-libs/transitions/src/schedule/due_tasks.js [hunk 1]
```diff
@@ -44,6 +44,12 @@ const updateScheduledTasks = (doc, context, dueDates, clearFailing=false) => {
   let updatedTasks = false;
   // set task to pending for gateway to pick up
   doc.scheduled_tasks.forEach(task => {
+    // only process tasks that are still in 'scheduled' state - skip tasks that have already
+    // progressed to other states (e.g. pending, sent, delivered) to prevent re-sending
+    if (task.state !== 'scheduled') {
```
Comment (dianabarsan) [inline shared-libs/transitions/src/schedule/due_tasks.js]: can you please add a constant for `scheduled`, and also change the query to use this constant?

File: shared-libs/transitions/test/unit/due_tasks.js [hunk 2]
```diff
@@ -1971,4 +1971,83 @@ describe('due tasks', () => {
...
+      assert.equal(doc.scheduled_tasks[0].state, 'sent', 'Task A (already sent) should not have its state changed');
+
+      // Task B should still be scheduled (message generation failed)
+      assert.equal(doc.scheduled_tasks[1].state, 'scheduled', 'Task B should remain scheduled');
+
+      // The document should NOT be saved since no valid state changes occurred
+      assert.equal(saveDoc.callCount, 0, 'Document should not be saved when no tasks were validly updated');
+    });
+  });
+
```
Comment (dianabarsan) [inline shared-libs/transitions/test/unit/due_tasks.js:2052]: Great unit testing! Can you please add an integration test as well here: https://github.com/medic/cht-core/blob/master/tests/integration/sentinel/schedules/due-tasks.spec.js#L371 by adding an additional report with one sent and one scheduled?

Comment (1yuv) [reply shared-libs/transitions/test/unit/due_tasks.js:2052]: Done.

File: shared-libs/transitions/src/schedule/due_tasks.js (hunk 1 above)
Comment (1yuv) [reply shared-libs/transitions/src/schedule/due_tasks.js]: Done.
