### PR TITLE
fix(#10357): prevent DEBUG logs from appearing in production

### LINKED ISSUE #10357: debug level messages printed on production instances
**Describe the bug**
Per CHT [documentation](https://docs.communityhealthtoolkit.org/hosting/cht/docker/logs/#setting-log-level), default log level is `info`, but we're seeing debug messages also printed on CHT API logs. 

**To Reproduce**
1. Go to your terminal and ensure you've access to the CHT production deployment. 
2. Run `kubectl -n instance_namespace logs cht-api-some-random-number | grep 'DEBUG`
3. You will see a lot of DEBUG entries. 

Alternatively, you can browse to observability if it's deployed, or medic's observability and search in the logs there. 

**Expected behavior**
Debug messages should not be logged if CHT's default log level is `info`. 

**Logs**
Below is the log from one of the Nepal's deployment. 

```
2025-10-07T13:25:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:26:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:27:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:28:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:29:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:30:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:31:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:32:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:33:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:34:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:35:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:36:17.360 DEBUG: Checking for a configured outgoing message service 
2025-10-07T13:37:17.360 DEBUG: Checking for a configured outgoing message service 
```

**Environment**
- Instance: Tested on nepal's production instances, probably everywhere else
- Client platform: Any
- App: API, possible everywhere else
- Version: ANY

### PR DESCRIPTION
**Pull request by sugat009**
## Summary

Fixes #10357 - DEBUG logs were appearing in production despite `NODE_ENV=production`.

### Changes:
  - Default `LOG_LEVEL` to `'info'` when not explicitly set in application code
  - Add `LOG_LEVEL: 'debug'` to CI workflow env (instead of repeating in each npm script)
  - Fix sentinel helm template to use `.Values.sentinel.log_level` instead of `.Values.api.log_level`
  - Add `sentinel.log_level` and `api.log_level` defaults to `base.yaml`

### Based on
  This PR is based on the work by @AmirSaudagar55 in #10376. Additional fixes were made to:
  - Resolve merge conflicts with master
  - Fix helm template values path for sentinel
  - Refactor `LOG_LEVEL=debug` from npm scripts to CI workflow env

# Code review checklist

- [ ] UI/UX backwards compatible: Test it works for the new design (enabled by default). And test it works in the old design, enable `can_view_old_navigation` permission to see the old design. Test it has appropriate design for RTL languages. 
- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10357-fix-debug-logs-v2/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10357-fix-debug-logs-v2/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10357-fix-debug-logs-v2/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by sugat009** [comment]
@jkuester Would appreciate a review on this. Thanks!

File: api/src/public/login/lib-bowser.js
Comment (jkuester) [inline api/src/public/login/lib-bowser.js:1]: Do we actually need changes to this file?  I am not sure exactly what triggers this to get updated.  Have we rebuilt these contents since you merged in the latest from master?

File: tests/utils/index.js [hunk 1]
```diff
@@ -1181,12 +1181,41 @@ const generateComposeFiles = async () => {
...
+
   for (const file of COMPOSE_FILES) {
     const templatePath = getTemplateComposeFilePath(file);
     const testComposePath = getTestComposeFilePath(file);
 
     const template = await fs.promises.readFile(templatePath, 'utf-8');
-    await fs.promises.writeFile(testComposePath, mustache.render(template, view));
+    let compiled = mustache.render(template, view);
+
+    INJECT_SERVICES.forEach((svc) => {
```
Comment (jkuester) [inline tests/utils/index.js]: 😬 as much as I love regex, I wonder if it might be better to just hardcode a `./tests/cht-core-test.override.yml file that sets the LOG_LEVEL envar.  We can commit that file and then update the `dockerComposeCmd` function above to include that file when running `docker compose` commands so the config is [merged](https://docs.docker.com/compose/how-tos/multiple-compose-files/merge/) with the default compose config.  

Seems a bit easier to manage than doing some regex mods here...

**Review by jkuester — CHANGES_REQUESTED** [review]
Thanks for keeping this going!  Just a couple minor things and this should be good to go!

---

Can we also get a docs PR to update the [log level documentation](https://docs.communityhealthtoolkit.org/hosting/cht/docker/logs/#setting-log-level)?

**Comment by jkuester** [comment]
Another thing that is worth considering is if we should update the `dev-api` and `dev-sentiel` commands to set `LOG_LEVEL=DEBUG`?  I think we want the debug logs when running in the development environment...

File: api/src/public/login/lib-bowser.js
Comment (sugat009) [reply api/src/public/login/lib-bowser.js:1]: I think this got pushed my mistake.

**Comment by sugat009** [comment]
> Thanks for keeping this going! Just a couple minor things and this should be good to go!
> 
> Can we also get a docs PR to update the [log level documentation](https://docs.communityhealthtoolkit.org/hosting/cht/docker/logs/#setting-log-level)?

Actually, there is already a PR for this. https://github.com/medic/cht-docs/pull/2030

File: tests/utils/index.js [hunk 2]
```diff
@@ -63,6 +63,7 @@ const CONTAINER_NAMES = {};
 const originalTranslations = {};
 const COUCH_USER_ID_PREFIX = 'org.couchdb.user:';
 const COMPOSE_FILES = ['cht-core', 'cht-couchdb-cluster'];
+const COMPOSE_OVERRIDE_FILE = path.resolve(__dirname, '../cht-core-test.override.yml');
```
Comment (mrjones-plip) [inline tests/utils/index.js:66]: Is the complexity of this external override file needed?  Couldn't we add a `LOG_LEVEL=${LOG_LEVEL:-info}` to the existing compose file(s) (rendered from [this template](https://github.com/medic/cht-core/blob/8f5902ad0031db093604565014049c47c7e6f3fa/scripts/build/cht-core.yml.template#L35)) and then in the `.env` file for testing just declare `LOG_LEVEL=debug`  for the services that need it?

we're possibly mirroring this functionality in [another PR](https://github.com/medic/cht-core/pull/10758#issuecomment-4130422611), so I was thinking on this some!

Comment (jkuester) [reply tests/utils/index.js:66]: > Couldn't we add a LOG_LEVEL=${LOG_LEVEL:-info} to the existing compose file(s) (rendered from [this template](https://github.com/medic/cht-core/blob/8f5902ad0031db093604565014049c47c7e6f3fa/scripts/build/cht-core.yml.template#L35))

My main concern for doing this is that `LOG_LEVEL` is a very generic envar.  I am not sure how good of an idea it is to automatically inherent that envar in our production docker compose config...

Comment (jkuester) [reply tests/utils/index.js:66]: Not opposed, just not sure what the best practices are here...

Comment (mrjones-plip) [reply tests/utils/index.js:66]: Ah - fair - we wouldn't want the wrong service to inherit the wrong log level value.

That said, a one time code audit + ad hoc testing feels like it'd be worth it now, vs the on going complexity of the extra file maybe?  

I'm willing to do both (code audit + ad hoc testing) if folks feel this is viable.  I don't feel strongly here, just saw an opportunity for an optimization.

Comment (jkuester) [reply tests/utils/index.js:66]: > a one time code audit + ad hoc testing feels like it'd be worth it now, vs the on going complexity of the extra file maybe

Sorry, to be clear, I am mostly concerned with the scenario where the _docker host_ already has `LOG_LEVEL=DEBUG` set for the shell.  Then, when the CHT is deployed with the compose config, it (perhaps unintentionally) has the log level set to `DEBUG`....

Comment (sugat009) [reply tests/utils/index.js:66]: The extra file is just for testing and not really impactful on production or on performance so I'm not sure if it's worth the effort.

File: tests/cht-core-test.override.yml [hunk 3]
```diff
@@ -0,0 +1,7 @@
+services:
+  api:
+    environment:
+      - "LOG_LEVEL=${LOG_LEVEL:-debug}"
+  sentinel:
+    environment:
+      - "LOG_LEVEL=${LOG_LEVEL:-debug}"
```
Comment (jkuester) [inline tests/cht-core-test.override.yml]:
```suggestion
      - "LOG_LEVEL=debug"
  sentinel:
    environment:
      - "LOG_LEVEL=debug"
```

Minor, but seems like we do not need to load any values from the local environment since this is just for our tests.  (Unless we really wanted to tap into the `DEBUG` envar that we use for other things in our e2e tests...)

File: package.json [hunk 4]
```diff
@@ -27,8 +27,8 @@
     "build-webapp-dev": "cd webapp && npm run build -- --configuration=development && npm run compile",
     "build-cht-form": "./scripts/build/build-prepare.sh && cd webapp && npm run build:cht-form",
     "copy-api-resources": "cp -r api/src/public/* api/build/static/",
-    "dev-api": "./scripts/build/copy-static-files.sh && (npm run --prefix shared-libs/cht-datasource build-watch & npm run --prefix api run-watch)",
-    "dev-sentinel": "npm run --prefix shared-libs/cht-datasource build-watch & npm run --prefix sentinel run-watch",
+    "dev-api": "export LOG_LEVEL=${LOG_LEVEL:-debug} && ./scripts/build/copy-static-files.sh && (npm run --prefix shared-libs/cht-datasource build-watch & npm run --prefix api run-watch)",
+    "dev-sentinel": "export LOG_LEVEL=${LOG_LEVEL:-debug}; npm run --prefix shared-libs/cht-datasource build-watch & npm run --prefix sentinel run-watch",
```
Comment (jkuester) [inline package.json]:
```suggestion
    "dev-api": "export LOG_LEVEL=debug && ./scripts/build/copy-static-files.sh && (npm run --prefix shared-libs/cht-datasource build-watch & npm run --prefix api run-watch)",
    "dev-sentinel": "export LOG_LEVEL=debug; npm run --prefix shared-libs/cht-datasource build-watch & npm run --prefix sentinel run-watch",
```

Same here.  If someone _really_ wants to change the log level that gets used with one of these scripts they can edit these lines....

**Review by jkuester — APPROVED** [review]
A couple minor suggestions around not reading the host `LOG_LEVEL` envar even for our test/development scripts. I am fine if you want to keep them as-is, but I just think it will be less complex to just hardcode the value (and might save some confusion in the future).
