### PR TITLE
fix(#10386): fix offline user and admin role detection

### LINKED ISSUE #10386: Purge database created for admin role
**Describe the bug**
I'm seeing purging databases for the `admin` role (medic user). This is an online role , so shouldn't have a purge database.  This wastes >6GB space and a lot of daily processing time. Since purging is struggling to complete on this instance, skipping the upkeep of this purge step and only handling roles which are known and valid would be a nice improvement 

**To Reproduce**
On Nairobi instance, I'm seeing purge database `medic-purged-role-6ed8e2e23ed4cf28156a7cd33ccc3f94` where the hash corresponds to the role `admin` which is undefined.

If this is a reserved role, it is online. If it is not a reserved role, it is undefined.

**Expected behavior**
There should not be a purging database for any online role including admin.

**Screenshots**

**Environment**
- Instance: nairobi 

**Additional context**
https://gitlab.echis.go.ke/echis-core/config-echis-2-0/-/issues/2941

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Admins are no longer `_admin` (since when?!!). Admins are now `admin` or have no role at all. 
This PR removes the purging specific `isOffline` code and calls the `user-management.roles.isOffline` instead. 
Also changes `user-management.roles.isOffline` to return `false` for empty roles and `false` for `admin` role. 

closes #10386

# Code review checklist

- [ ] UI/UX backwards compatible: Test it works for the new design (enabled by default). And test it works in the old design, enable `can_view_old_navigation` permission to see the old design. Test it has appropriate design for RTL languages. 
- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10386-no-admin-purge-dbs/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10386-no-admin-purge-dbs/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10386-no-admin-purge-dbs/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
@jkuester tiny nudge in case this one slipped through the cracks. Please let me know if you'd like me to reassign it if you're to stretched out.

File: shared-libs/user-management/src/roles.js [hunk 1]
```diff
@@ -7,21 +6,21 @@ const { USER_ROLES } = require('@medic/constants');
...
-const DB_ADMIN_ROLE = '_admin';
+const DB_ADMIN_ROLES = ['admin', '_admin'];
 
 const hasRole = (userCtx, role) => {
-  return _.includes(userCtx && userCtx.roles, role);
+  return userCtx?.roles?.includes(role);
 };
 
-const isDbAdmin = userCtx => hasRole(userCtx, DB_ADMIN_ROLE);
+const isDbAdmin = userCtx => DB_ADMIN_ROLES.some(adminRole => hasRole(userCtx, adminRole));
```
Comment (jkuester) [inline shared-libs/user-management/src/roles.js:15]: So, I think we are still ending up with some inconsistency here with the [permissions logic in cht-datasorce](https://github.com/medic/cht-core/blob/59b42e2fa3271a69c713b4720b9ee9fb7ea3dc61/shared-libs/cht-datasource/src/auth.js#L9).  

What do you think about updating cht-datasource to expose the `isAdmin` function so that we can consume it here (and anywhere else where we do the DB admin check.

Eventually it seems like we should consider moving more of this `roles.js` logic that needs to be reused outside of user-management over to cht-datasource, but that does not need to happen at this time...

File: shared-libs/user-management/src/roles.js [hunk 2]
```diff
@@ -41,10 +40,15 @@ module.exports = {
     return userCtx && module.exports.hasOnlineRole(userCtx.roles);
   },
   isOffline: roles => {
+    if (!roles.length) {
+      return false;
+    }
+
```
Comment (jkuester) [inline shared-libs/user-management/src/roles.js:46]: This should not break any existing users/instances, right? It makes me a bit nervous since it is definitely a change from the previous behavior, but I don't think it is possible for a user to login without a role.  So, it should not be possible to make it here with empty roles anyway.....

File: shared-libs/user-management/src/users.js [hunk 3]
```diff
@@ -619,7 +619,7 @@ const saveUserSettingsUpdates = async (userSettings) => {
 
 const validateFacilityIsNeeded = (data, user) => {
   const userRoles = data.roles || user?.roles;
-  if (userRoles && roles.isOffline(userRoles)) {
+  if (userRoles && userRoles.length && roles.isOffline(userRoles)) {
```
Comment (jkuester) [inline shared-libs/user-management/src/users.js]: We don't actually need to check the `length` here (or below), right?  The `isOffline` logic now should return `false` if the given array is empty....

Comment (dianabarsan) [reply shared-libs/user-management/src/users.js]: I initially didn't want to change `isOffline` to check for roles length. And then ended up having this in two places.

File: shared-libs/user-management/src/roles.js (hunk 2 above)
Comment (dianabarsan) [reply shared-libs/user-management/src/roles.js:46]: I just checked, and users without roles are definitely broken. They are considered offline and they download their docs (assuming that everything is setup and they have a facility) and then the sync fails when they try to create the checkpointer document on the server, because they are not allowed to make changes to the `medic` database. 

I think we need better guarging for users without roles. The behavior of not being able to access the DB will persist even if the app doesn;t believe they are offline users.

File: shared-libs/user-management/src/roles.js (hunk 1 above)
Comment (dianabarsan) [reply shared-libs/user-management/src/roles.js:15]: I'm not sure. I don't think I like bloating datasource with _everything_.

Comment (jkuester) [reply shared-libs/user-management/src/roles.js:15]: image


I am cool with whatever you think is best here.  Def agree that not everything belongs in cht-datasource, but at the same time I really hate duplicated logic. It is weird to have multiple places in the code controlling permissions. But, currently this is really minor logic, so no need to get too crazy with things right now... (Maybe in the future we need _another_ shared-lib for permissions that cht-datasource can depend on.... :sweat_smile:  :facepalm: )

Comment (dianabarsan) [reply shared-libs/user-management/src/roles.js:15]: I think the shared lib for permissions makes sense. i know you said it as a joke, but I really think that modules that handle _one_ think are so much easier to grasp than one gigantic module that handles everything. datasource should handle ... what it's name says, communication with the DB, and nothing else.
